### Set VCHOME to VC directory 
VCHOME = D:\applications\compilers\VC98
VCINCLUDE=$(VCHOME)\include 
INCLUDE = $(VCINCLUDE)
LIB = $(VCHOME)\lib

CC= cl
## /G6 for Pentium Pro , \GB for generic make

## CFLAGS=	-Ox /G6 /c  -I$(VCINCLUDE)
CFLAGS=	-Ox /GB /c  -I$(VCINCLUDE)

MODULES=	frprmn.c linmin.c brent.c mnbrak.c nrutil.c

OBJECTS = $(MODULES:.c=.obj)

nrc: $(OBJECTS) 
	link /OUT:nrfoptGB.dll /DLL /MAP /IMPLIB:nrfoptGB.lib $(VCHOME)\lib\BINMODE.OBJ $(OBJECTS)
	cp nrfoptGB.* ..



